config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

resources :projects do
  resources :inline_issues do
    collection do
      get :edit_multiple
    end
  end
end

resources :inline_issues do
  collection do
    get :edit_multiple
    put :update_multiple
  end
end


  

app/helpers/inline_issues_helper.rb
module InlineIssuesHelper
  include CustomFieldsHelper
  include ProjectsHelper

  def inline_project_id
    @project.present? ? @project.id : ""
  end

  def column_form_content(column, issue, f)
    if column.class.name == "QueryCustomFieldColumn"
      custom_field_values = issue.editable_custom_field_values
      value = custom_field_values.detect { |cfv| cfv.custom_field_id == column.custom_field.id }
      custom_field_tag :issues, value, issue, f if value.present?
    else
      case column.name
      when :tracker
        f.select :tracker_id, issue.project.trackers.collect { |t| [t.name, t.id] }
      when :status
        f.select :status_id, issue.new_statuses_allowed_to.collect { |p| [p.name, p.id] }
      when :priority
        f.select :priority_id, @priorities.collect { |p| [p.name, p.id] }
      when :subject
        f.text_field :subject, size: 20
      when :assigned_to
        f.select :assigned_to_id, principals_options_for_select(issue.assignable_users, issue.assigned_to), :include_blank => true
      when :estimated_hours
        f.text_field :estimated_hours, size: 3
      when :start_date
        f.date_field(:start_date, size: 8) +
            calendar_for('issues_' + issue.id.to_s + '_start_date')
      when :due_date
        f.date_field(:due_date, size: 8) +
            calendar_for('issues_' + issue.id.to_s + '_due_date')
      when :done_ratio
        f.select :done_ratio, ((0..10).to_a.collect { |r| ["#{r * 10} %", r * 10] })
      when :is_private
        f.check_box :is_private
      when :description
        f.text_area :description
      when :category
        f.select :category_id, [["", ""]] + issue.project.issue_categories.collect { |t| [t.name, t.id] }
      when :fixed_version
        f.select :fixed_version_id, [["", ""]] + issue.project.versions.collect { |t| [t.name, t.id] }
      when :relations
        render_issue_relations_form(issue, f)
      else
        column_display_text(column, issue)
      end
    end
  end

  def column_display_text(column, issue)
    begin
      value = column.value(issue)
    rescue NoMethodError => e
      # Redmine 6 compatibility: Handle dot-notation columns like 'parent.subject'
      value = column.value_object(issue) if column.respond_to?(:value_object)
      value ||= ''
    end

    case value.class.name
    when 'Time'
      format_time(value)
    when 'Date'
      format_date(value)
    when 'Float'
      sprintf "%.2f", value
    when 'TrueClass'
      l(:general_text_Yes)
    when 'FalseClass'
      l(:general_text_No)
    else
      h(value)
    end
  end

  def column_total(column, issues)
    case column.name
    when :estimated_hours
      totalEstHours(issues)
    when :spent_hours
      totalSpentHours(issues)
    end
  end

  def group_column_total(column, issues, group)
    case column.name
    when :estimated_hours
      totalGroupEstHours(issues, group)
    when :spent_hours
      totalGroupSpentHours(issues, group)
    end
  end

  def inline_edit_condition
    # @idsが空の場合は条件なし（全チケットを対象）
    if @ids.present?
      "issues.id in (#{@ids.map { |i| i.to_i }.join(',')})"
    else
      nil
    end
  end

  def group_class_name(group)
    begin
      if group.present?
        # strip out white spaces from the group name
        "group_" + group.name.gsub(/\s+/, "")
      else
        ""
      end
    rescue
      ""
    end
  end

  def group_total_name(group, column)
    if group.present? && column.present?
      "#{group_class_name(group)}_total_#{column.name}"
    else
      ""
    end
  end

  def render_issue_relations_form(issue, f)
    content = ''.html_safe
    
    # Display existing relations with delete checkboxes
    issue.relations.each do |relation|
      other_issue = relation.other_issue(issue)
      next unless other_issue && other_issue.visible?
      
      relation_label = "#{relation.label_for(issue)} ##{other_issue.id}"
      checkbox_name = "issues[#{issue.id}][delete_relation_ids][]"
      
      content << content_tag(:div, class: 'relation-item') do
        check_box_tag(checkbox_name, relation.id, false, id: "issue_#{issue.id}_delete_relation_#{relation.id}") +
        label_tag("issue_#{issue.id}_delete_relation_#{relation.id}", "#{l(:button_delete)} #{relation_label}")
      end
    end
    
    # Get available issues for the datalist
    available_issues = Issue.visible
                            .where(project_id: issue.project_id)
                            .where.not(id: issue.id)
                            .order(id: :desc)
                            .limit(500)
                            .pluck(:id, :subject)
    
    datalist_id = "issue_#{issue.id}_available_issues"
    
    # Add new relation fields
    content << content_tag(:div, class: 'add-relation') do
      select_html = select_tag(
        "issues[#{issue.id}][new_relation_type]",
        options_for_select([
          ['', ''],
          [l(:label_relates_to), IssueRelation::TYPE_RELATES],
          [l(:label_duplicates), IssueRelation::TYPE_DUPLICATES],
          [l(:label_duplicated_by), IssueRelation::TYPE_DUPLICATED],
          [l(:label_blocks), IssueRelation::TYPE_BLOCKS],
          [l(:label_blocked_by), IssueRelation::TYPE_BLOCKED],
          [l(:label_precedes), IssueRelation::TYPE_PRECEDES],
          [l(:label_follows), IssueRelation::TYPE_FOLLOWS],
          [l(:label_copied_to), IssueRelation::TYPE_COPIED_TO],
          [l(:label_copied_from), IssueRelation::TYPE_COPIED_FROM]
        ]),
        class: 'relation-type'
      )
      
      issue_field = text_field_tag(
        "issues[#{issue.id}][new_relation_issue_id]",
        '',
        placeholder: '#123',
        size: 12,
        class: 'relation-issue-id',
        list: datalist_id
      )
      
      datalist = content_tag(:datalist, id: datalist_id) do
        available_issues.map do |id, subject|
          content_tag(:option, value: id) do
            "##{id} - #{subject.truncate(50)}"
          end
        end.join.html_safe
      end
      
      select_html + ' ' + issue_field + datalist
    end
    
    content
  end

  private

  def totalEstHours(issues)
    estTotal = 0
    issues.each { |i| estTotal += i.estimated_hours if i.estimated_hours.present? }
    sprintf "%.2f", estTotal
  end

  def totalSpentHours(issues)
    spentTotal = 0
    issues.each { |i| spentTotal += i.spent_hours if i.spent_hours.present? }
    sprintf "%.2f", spentTotal
  end

  def totalGroupEstHours(issues, group)
    estTotal = 0
    issues.each do |i|
      if i.estimated_hours.present? && @query.group_by_column.value(i) == group
        estTotal += i.estimated_hours
      end
    end
    sprintf "%.2f", estTotal
  end

  def totalGroupSpentHours(issues, group)
    spentTotal = 0
    issues.each do |i|
      if i.spent_hours.present? && @query.group_by_column.value(i) == group
        spentTotal += i.spent_hours
      end
    end
    sprintf "%.2f", spentTotal
  end


  #####
  # Return custom field html tag corresponding to its format
  #####
  def custom_field_tag(name, custom_value, issue, f)
    custom_field = custom_value.custom_field
    field_name = "#{name}[#{issue.id}][custom_field_values][#{custom_field.id}]"
    field_name << "[]" if custom_field.multiple?
    field_id = "#{name}_custom_field_values_#{custom_field.id}"

    tag_options = {:id => field_id, :class => "#{custom_field.field_format}_cf"}

    field_format = Redmine::FieldFormat.find(custom_field.field_format)

    case custom_field.field_format
    when "attachment"
      #render :partial => 'attachments/form', :locals => {:container => issue}
    when "user"
      assignable_users = (issue.project.assignable_users.to_a + [issue.project.default_assigned_to]).uniq.compact
      blank_option = content_tag('option', "--- #{l(:actionview_instancetag_blank_option)} ---", :value => '')
      select_tag(field_name, blank_option + principals_options_for_select(assignable_users, custom_value.value))
    when "version"
      blank_option = content_tag('option', "--- #{l(:actionview_instancetag_blank_option)} ---", :value => '')
      select_tag(field_name, blank_option + version_options_for_select(issue.assignable_versions, custom_value.value))
    when "date"
      date_field_tag(field_name, custom_value.value, tag_options.merge(:size => 10)) +
          calendar_for(field_id)
    when "text"
      text_area_tag(field_name, custom_value.value, tag_options.merge(:rows => 4, :cols => 65, :style => "width:auto; resize:both;"))
    when "bool"
      custom_value.custom_field.format.edit_tag self,
                                                field_id,
                                                field_name,
                                                custom_value,
                                                :class => "#{custom_value.custom_field.field_format}_cf"
    when "list"
    when "enumeration"
      blank_option = ''.html_safe
      unless custom_field.multiple?
        if custom_field.is_required?
          unless custom_field.default_value.present?
            blank_option = content_tag('option', "--- #{l(:actionview_instancetag_blank_option)} ---", :value => '')
          end
        else
          blank_option = content_tag('option')
        end
      end
      s = select_tag(field_name, blank_option + options_for_select(custom_field.possible_values_options(custom_value.customized), custom_value.value),
                     tag_options.merge(:multiple => custom_field.multiple?, :id => (issue.id.to_s + '_' + custom_field.name.to_s + '_enum').parameterize.underscore))
      if custom_field.multiple?
        s << hidden_field_tag(field_name, '')
      end
      s
    else
      text_field_tag(field_name, custom_value.value, tag_options)
    end
  end

end

app/views/inline_issues/_context_menu_hook.html.erb
<% if params[:back_url].present? %>
    <li>
    	<%
    	uri = URI.parse(params[:back_url])
    	if uri.query.present?
	    	args = CGI.parse(uri.query)
	    	col = args.keys.include?('c[]') ? args['c[]'] : nil
	    end
	    # 常に全チケットを表示するため、idsパラメータはnilにする
	    ids_param = nil
    	%>
        <%= context_menu_link l(:button_inline_edit), @project ? edit_multiple_project_inline_issues_path(@project, :ids => ids_param, :c => col) : edit_multiple_inline_issues_path(:ids => ids_param, :back_url => params[:back_url], :c => col), :disabled => !@can[:edit] %>
    </li>
<% end %>

app/views/inline_issues/_edit_form.html.erb
<%= form_tag @update_url, :id => 'inline_edit_form', method: :put do %>
  <%= hidden_field_tag 'back_url', @back_url %>
  <div class="autoscroll">
    <table class="list issues">
      <thead>
      <% @query_inline_columns.each do |column| %>
        <%= column_header(@query, column) %>
      <% end %>
      </thead>
      <% previous_group = false %>
      <tbody>
      <% @issues.each do |issue| %>
        <%= fields_for "issues[]", issue do |f| %>
          <% if @query.grouped? && (group = @query.group_by_column.value(issue)) != previous_group %>
            <% reset_cycle %>

            <% if previous_group %>
              <%= render 'group_totals', group: previous_group, query: @query %>
            <% end %>

            <tr class="group open">
              <td colspan="<%= @query_inline_columns.size + 2 %>">
                <span class="expander" onclick="toggleRowGroup(this);">&nbsp;</span>
                <%= group.blank? ? l(:label_none) : column_content(@query.group_by_column, issue) %>
                <span class="count"><%= @issue_count_by_group[group] %></span>
                <%= link_to_function("#{l(:button_collapse_all)}/#{l(:button_expand_all)}", "toggleAllRowGroups(this)", :class => 'toggle-all') %>
              </td>
            </tr>
            <% previous_group = group %>
          <% end %>
          <tr id="issue-<%= issue.id %>" class="hascontextmenu <%= cycle('odd', 'even') %> <%= issue.css_classes %> ">
            <% @query_inline_columns.each do |column| %>
              <td class="<%= column.css_classes %> <%= group_class_name(group) %>"> <%= column_form_content(column, issue, f) %> </td>
            <% end %>
          </tr>
        <% end %>
      <% end %>
      <% if previous_group %>
        <%= render 'group_totals', group: previous_group, query: @query %>
      <% end %>
      <tr class="inline_totals">
        <% @query_inline_columns.each do |column| %>
          <td id="total-<%= column.name %>"><%= column_total(column, @issues) %></td>
        <% end %>
      </tr>
      
      <!-- New issue rows -->
      <%= render 'new_issue_fields', query: @query, project: @project %>
      
      <!-- Add button row -->
      <tr>
        <td colspan="<%= @query_inline_columns.size %>" style="text-align: right; padding: 10px;">
          <button type="button" id="add-new-issue-row" style="padding: 4px 12px; background: #5cb85c; color: white; border: none; border-radius: 3px; cursor: pointer; font-size: 18px; font-weight: bold;">+</button>
        </td>
      </tr>
      </tbody>
    </table>
  </div>
  <%= submit_tag l(:button_submit) %>
  <input name="resetform" type="reset" id="inline_edit_reset" value="Reset"/>
  <%= link_to l(:button_cancel), @back_url %>
<% end %>

app/views/inline_issues/_group_totals.html.erb
<tr class="group inline_group_totals">
    <% query.inline_columns.each do |column| %>
        <td id=<%= group_total_name(group, column) %>><%= group_column_total(column, @issues, group)%></td>
    <% end %>
</tr>

app/views/inline_issues/_new_issue_fields.html.erb
<tr class="new-issue-row-data" data-index="0">
  <%
    # トラッカー列が含まれているか確認
    has_tracker_column = @query_inline_columns.any? { |c| c.name == :tracker }
  %>
  
  <% unless has_tracker_column %>
    <%# トラッカー列がない場合は、hidden fieldでデフォルトトラッカーを設定 %>
    <%= hidden_field_tag 'new_issues[0][tracker_id]', @default_tracker&.id, class: 'new-issue-tracker' %>
  <% end %>
  
  <% @query_inline_columns.each_with_index do |column, index| %>
    <td class="<%= column.css_classes %>">
      <% case column.name %>
      <% when :tracker %>
        <%= select_tag 'new_issues[0][tracker_id]', 
            options_for_select(project.trackers.collect { |t| [t.name, t.id] }, @default_tracker&.id), 
            include_blank: true,
            class: 'new-issue-tracker' %>
      <% when :subject %>
        <%= text_field_tag 'new_issues[0][subject]', '', 
            placeholder: l(:field_subject),
            class: 'new-issue-subject',
            size: 20 %>
      <% when :status %>
        <% 
          # デフォルトトラッカーのデフォルトステータスを取得
          initial_statuses = @default_tracker && @tracker_statuses[@default_tracker.id] ? @tracker_statuses[@default_tracker.id] : []
          default_status_id = @default_tracker && @tracker_default_status_ids[@default_tracker.id] ? @tracker_default_status_ids[@default_tracker.id] : nil
        %>
        <%= select_tag 'new_issues[0][status_id]', 
            options_for_select(initial_statuses.collect { |id, name| [name, id] }, default_status_id),
            class: 'new-issue-status',
            data: { 
              tracker_statuses: @tracker_statuses.to_json,
              tracker_default_status_ids: @tracker_default_status_ids.to_json 
            } %>
      <% when :priority %>
        <%= select_tag 'new_issues[0][priority_id]', 
            options_for_select(IssuePriority.active.collect { |p| [p.name, p.id] }, @default_priority_id),
            class: 'new-issue-priority' %>
      <% when :assigned_to %>
        <%= select_tag 'new_issues[0][assigned_to_id]', 
            options_for_select(project.assignable_users.collect { |u| [u.name, u.id] }, @default_assigned_to_id), 
            include_blank: true,
            class: 'new-issue-assigned-to' %>
      <% when :fixed_version %>
        <%= select_tag 'new_issues[0][fixed_version_id]', 
            options_for_select(project.shared_versions.collect { |v| [v.name, v.id] }), 
            include_blank: true,
            class: 'new-issue-version' %>
      <% when :start_date %>
        <%= date_field_tag 'new_issues[0][start_date]', '', 
            class: 'new-issue-start-date',
            size: 8 %>
      <% when :due_date %>
        <%= date_field_tag 'new_issues[0][due_date]', '', 
            class: 'new-issue-due-date',
            size: 8 %>
      <% when :description %>
        <%= text_area_tag 'new_issues[0][description]', '', 
            placeholder: l(:field_description),
            class: 'new-issue-description',
            rows: 2 %>
      <% when :category %>
        <%= select_tag 'new_issues[0][category_id]', 
            options_for_select(project.issue_categories.collect { |c| [c.name, c.id] }, @default_category_id), 
            include_blank: true,
            class: 'new-issue-category' %>
      <% when :estimated_hours %>
        <%= text_field_tag 'new_issues[0][estimated_hours]', '', 
            size: 3,
            class: 'new-issue-estimated-hours' %>
      <% when :done_ratio %>
        <%= select_tag 'new_issues[0][done_ratio]', 
            options_for_select(((0..10).to_a.collect { |r| ["#{r * 10} %", r * 10] }), @default_done_ratio),
            include_blank: true,
            class: 'new-issue-done-ratio' %>
      <% else %>
        <!-- 他の列は空白 -->
      <% end %>
      
      <% # 最後の列に削除ボタンを追加 %>
      <% if index == @query_inline_columns.size - 1 %>
        <button type="button" class="remove-new-issue" style="display:none; padding: 2px 8px; background: #d9534f; color: white; border: none; border-radius: 3px; cursor: pointer; font-size: 16px; font-weight: bold; margin-left: 5px;">-</button>
      <% end %>
    </td>
  <% end %>
</tr>

app/views/inline_issues/_options_form.html.erb
<%= form_tag({ :controller => 'inline_issues', :action => 'edit_multiple', :project_id => @project, :ids => @ids },
            :method => :get, :id => 'query_form') do %>
    <%= hidden_field_tag 'set_filter', '1' %>
    <%= hidden_field_tag 'ids', @ids %>
    <%= hidden_field_tag 'project_id', @project.id %>
    <div id="query_form_content" class="hide-when-print">
    <fieldset class="collapsible collapsed">
      <legend onclick="toggleFieldset(this);"><%= l(:label_options) %></legend>
      <div style="display: none;">
        <table>
          <tr>
            <td><%= l(:field_column_names) %></td>
            <td><%= render_query_columns_selection(@query) %></td>
          </tr>
          <tr>
            <td><label for='group_by'><%= l(:field_group_by) %></label></td>
            <td><%= select_tag('group_by',
                               options_for_select(
                                 [[]] + @query.groupable_columns.collect {|c| [c.caption, c.name.to_s]},
                                 @query.group_by)
                       ) %></td>
          </tr>
          <tr>
            <td><%= l(:button_show) %></td>
            <td><%= available_block_columns_tags(@query) %></td>
          </tr>
        </table>
      </div>
    </fieldset>
    </div>
    <p class="buttons hide-when-print">

    <%= link_to_function l(:button_apply), '$("#query_form").submit()', :class => 'icon icon-checked' %>
    <%= link_to l(:button_clear), { :set_filter => 1, :project_id => @project, :ids => @ids }, :class => 'icon icon-reload'  %>
    <% if @query.new_record? && User.current.allowed_to?(:save_queries, @project, :global => true) %>
        <%= link_to_function l(:button_save),
                             "$('#query_form').attr('action', '#{ @project ? new_project_query_path(@project) : new_query_path }'); submit_query_form('query_form')",
                             :class => 'icon icon-save' %>
    <% end %>
    </p>
<% end %>

app/views/inline_issues/edit_multiple.html.erb
<h2><%= l(:label_inline_edit_selected_issues) %></h2>
<%= render 'edit_form'%>

<div id="field_original">
    <div id="field_original_value">#</div>
</div>

<% content_for :header_tags do %>
  <%= stylesheet_link_tag "inline_edit_issues", plugin: "redmine_inline_edit_issues" %>
  <%= javascript_include_tag "inline_edit_issues", plugin: "redmine_inline_edit_issues" %>
<% end %>